src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/accountmanagement/contentalerts/ManageContentAlertsBean.java
package org.cambridge.ebooks.orgadmin.accountmanagement.contentalerts;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.jpa.user.Login;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.ebooks.online.util.HttpUtil;

public class ManageContentAlertsBean {
	private static final Logger LOGGER = Logger.getLogger(ManageContentAlertsBean.class);
	private boolean hasError;
	
	public String getInitialize(){

		LOGGER.info("getInitialize");
    	
    	HttpServletRequest request = HttpUtil.getHttpServletRequest();
		OrgConLinkedMap orgConLinkedMap = OrgConLinkedMap.getFromSession(request);		
		Login login = orgConLinkedMap.getUserLogin();
				
		if(null == login) {
			HttpUtil.redirect(request.getContextPath() +"/orgadmin/account_management.jsf?page=register");
//			try {
//				HttpUtil.getHttpServletResponse().sendRedirect("/orgadmin/account_management.jsf?page=register");
//			} catch (IOException e) {
//				e.printStackTrace();
//			}
		}
		
		return "";
	}
	
	public boolean isHasError() {
		return hasError;
	}

	public void setHasError(boolean hasError) {
		this.hasError = hasError;
	}
}

src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/accountmanagement/register/ChangeRegistrationDetailsBean.java
package org.cambridge.ebooks.orgadmin.accountmanagement.register;

import java.util.LinkedHashMap;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.countrystates.CountryStateMapWorker;
import org.cambridge.ebooks.online.jpa.user.Login;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.ebooks.online.util.HttpUtil;


public class ChangeRegistrationDetailsBean {
	
	private Register userDetails;
	private LinkedHashMap<String, String> countryList;
	private LinkedHashMap<String, String> countyList;
	

	private static Logger LOGGER = Logger.getLogger(ChangeRegistrationDetailsBean.class);
	public String getInitialize(){
		HttpServletRequest request = HttpUtil.getHttpServletRequest();
		OrgConLinkedMap orgConLinkedMap = OrgConLinkedMap.getFromSession(request);		
		Login login = orgConLinkedMap.getUserLogin();
		//orgConLinkedMap.get
		if(null==login){
			HttpUtil.redirect(request.getContextPath() + "/orgadmin/account_management.jsf");
			
		} else {
			LOGGER.info("==updateRegisterBean");
			LOGGER.info(login.getMemberId());
			setUserDetails(login.getMemberId());
			setCountryList(new CountryStateMapWorker().getCountryMap());
			String countryId = userDetails.getCountry(); //unitedstates(default)
			setCountyList(RegisterWorker.getCountyListById(countryId ));
		}
		
		
		return "";
	}
	private void setUserDetails(String memberId) {
		Register userDetails = ChangeRegistrationWorker.getUserDetails(memberId);
//		userDetails.setQuestion(otherdetails.getQuestion());
//		userDetails.setFax(otherdetails.getFax());
//		userDetails.setAffiliation(otherdetails.getAffiliation());
//		userDetails.setSmsAlert(otherdetails.isSmsAlert());
//		userDetails.setEmailList(otherdetails.isEmailList());
//		userDetails.setThirdParty(otherdetails.isThirdParty());
//		
		this.userDetails = userDetails;
	}
	
	public void setUserDetails(Register userDetails) {
		this.userDetails = userDetails;
	}
	public Register getUserDetails() {
		return userDetails;
	}
	public LinkedHashMap<String, String> getCountryList() {
		return countryList;
	}
	public void setCountryList(LinkedHashMap<String, String> countryList) {
		this.countryList = countryList;
	}
	public LinkedHashMap<String, String> getCountyList() {
		return countyList;
	}
	public void setCountyList(LinkedHashMap<String, String> countyList) {
		this.countyList = countyList;
	}
}

src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/accountmanagement/register/ChangeRegistrationServlet.java
package org.cambridge.ebooks.orgadmin.accountmanagement.register;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.jpa.user.Login;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.util.UnixCrypt;

public class ChangeRegistrationServlet extends HttpServlet {
	private static final long serialVersionUID = -5910230138565404510L;
	private static Logger LOGGER = Logger.getLogger(ChangeRegistrationServlet.class);
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request,response);
	}
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {		
		LOGGER.info("==updateRegServlet");
		
		if(StringUtils.isNotEmpty(request.getParameter("update"))){
			OrgConLinkedMap orgConLinkedMap = OrgConLinkedMap.getFromSession(request);		
			Login login = orgConLinkedMap.getUserLogin();
			
			if(null == login) {
				response.sendRedirect(request.getContextPath() + "/home.jsf");
			} else {
				String offerCode = request.getParameter("offerCode");
				boolean isPromotionCode = thisIsPromotionCode( offerCode );
				
				String username = request.getParameter("userName");
				String password = request.getParameter("oldPassWord");
				
				if(matchOldPassword(username, password)){
					Register userUpdate = setChanges(request);
					
					String errorMsg = ChangeRegistrationWorker.updateUser(userUpdate);
					
					if(StringUtils.isEmpty(errorMsg)){
						ChangeRegistrationWorker.updateBladePrefAndMember(userUpdate);
						
						if( isPromotionCode ){
							String memberId = login.getMemberId();
							ChangeRegistrationWorker.processSubscriptionCode(memberId, userUpdate.getUserName(),offerCode, request);
						}
						RequestDispatcher rd = request.getRequestDispatcher("/orgadmin/account_management.jsf?page=up_success");
						rd.forward(request, response);
					}
					LOGGER.info(errorMsg);
				}
			}
		} else {
			response.sendRedirect("/orgadmin/account_management.jsf?page=updateReg");
		}
	}


	private boolean matchOldPassword(String username, String password) {
		String oldPassword = ChangeRegistrationWorker.getOldPassword(username);
		boolean matches = UnixCrypt.matches(oldPassword, password)|| oldPassword.equals(password);
		
		return matches;
	}

	private boolean thisIsPromotionCode(String offerCode) {
		if(StringUtils.isEmpty(offerCode)){
			offerCode = "";
		}
		return offerCode.startsWith( "8379" );	
	}
	
	private Register setChanges(HttpServletRequest request) {
		Register reg = new Register();
		reg.setTitle(request.getParameter("title"));
		reg.setFirstName(request.getParameter("firstName"));
		reg.setSurName(request.getParameter("surName"));
		//reg.setOrg(request.getParameter("organisation"));
		reg.setAdmin("on".equals(request.getParameter("admin")));
		reg.setAddress(request.getParameter("admin"));
		reg.setCountry(request.getParameter("country"));
		reg.setState(request.getParameter("state"));
		reg.setCity(request.getParameter("city"));
		reg.setPostCode(request.getParameter("postCode"));
		reg.setAddress(request.getParameter("address"));
		reg.setAddress2(request.getParameter("address2"));
		reg.setTelephone(request.getParameter("telephone"));
		reg.setUserName(request.getParameter("userName"));
		if(StringUtils.isNotEmpty(request.getParameter("passWord"))){
			reg.setPassWord(request.getParameter("passWord"));
		} else {
			reg.setPassWord(request.getParameter("oldPassWord"));
		}
		reg.setEmail(request.getParameter("email"));
		reg.setQuestion(request.getParameter("question"));
		reg.setAcceptTerms("on".equals(request.getParameter("acceptTerms")));
		reg.setEmailList("on".equals(request.getParameter("emailList")));
		reg.setThirdParty("on".equals(request.getParameter("thirdParty")));
		reg.setSmsAlert("on".equals(request.getParameter("smsAlert")));
		reg.setOfferCode(request.getParameter("offerCode"));
		
		return reg;
	}
}

src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/accountmanagement/register/RegisterBean.java
package org.cambridge.ebooks.orgadmin.accountmanagement.register;
/**
 * @author cemanalo
 */
import java.util.LinkedHashMap;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.countrystates.CountryStateMapWorker;
import org.cambridge.ebooks.online.jpa.user.Login;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.ebooks.online.util.HttpUtil;

public class RegisterBean {
	private static Logger LOGGER = Logger.getLogger(RegisterBean.class);
			
	private LinkedHashMap<String, String> countryList;
	private LinkedHashMap<String, String> countyList;
	private LinkedHashMap<String, String> errorMap;
	
	public String getInitialize(){
		LOGGER.info("===getInitialize");
		HttpServletRequest request = HttpUtil.getHttpServletRequest();
		OrgConLinkedMap orgConLinkedMap = OrgConLinkedMap.getFromSession(request);		
		Login login = orgConLinkedMap.getUserLogin();
		
		if(null==login){
			setCountryList(new CountryStateMapWorker().getCountryMap());
			String countryId = "226"; //unitedstates(default)
			setCountyList(RegisterWorker.getCountyListById(countryId ));
			//setErrorMap(RegisterWorker.getErrorMessages(request));
			
		} else {
//			String url = request.getContextPath() + "/orgadmin/account_management.jsf?page=updateReg";
//			try {
//				 HttpServletResponse response = HttpUtil.getHttpServletResponse();
//				response.sendRedirect(url);
//				//FacesContext.getCurrentInstance().getExternalContext().redirect(url);
//			} catch (IOException e) {
//				e.printStackTrace();
//			}
			HttpUtil.redirect(request.getContextPath() + "/orgadmin/account_management.jsf?page=updateReg");
		}
		
		
		return "";
	}

	public void setCountyList(LinkedHashMap<String, String> countyList) {
		this.countyList = countyList;
	}

	public LinkedHashMap<String, String> getCountyList() {
		return countyList;
	}

	public void setCountryList(LinkedHashMap<String, String> countryList) {
		this.countryList = countryList;
	}

	public LinkedHashMap<String, String> getCountryList() {
		return countryList;
	}

	public void setErrorMap(LinkedHashMap<String, String> errorMap) {
		this.errorMap = errorMap;
	}

	public LinkedHashMap<String, String> getErrorMap() {
		return errorMap;
	}

	
	

	
}

src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/accountmanagement/register/RegisterServlet.java
package org.cambridge.ebooks.orgadmin.accountmanagement.register;

import java.io.IOException;
import java.util.LinkedHashMap;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.internal_reports.InternalReportsWorker;
import org.cambridge.ebooks.online.jpa.user.StringUtil;
import org.cambridge.ebooks.online.jpa.user.User;
import org.cambridge.ebooks.online.login.CJOLoginBean;
import org.cambridge.ebooks.online.login.ConfirmationBean;
import org.cambridge.ebooks.online.login.LoginServlet;
import org.cambridge.ebooks.online.login.RelogBean;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.ebooks.online.organisation.OrganisationWorker;
import org.cambridge.ebooks.online.subscription.FreeTrialBean;
import org.cambridge.ebooks.online.subscription.SubscriptionBean;
import org.cambridge.ebooks.online.user.UserWorker;
import org.cambridge.util.UnixCrypt;
public class RegisterServlet extends HttpServlet {
	private static final long serialVersionUID = -5910230138565404510L;
	
	private static final Logger LOGGER = Logger.getLogger(RegisterServlet.class);
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request,response);
	}
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {		
		LOGGER.info("==registerServlet");
		OrgConLinkedMap orgConLinkedMap = OrgConLinkedMap.getFromSession(request);
		
		if(null==orgConLinkedMap.getCurrentlyLoggedBodyId()){
			if (null != request.getParameter("register")){
				
				final int SUCCESS = 0;
				Register register = setRegister(request);
				
				int ret = RegisterWorker.addUser(register);
				LinkedHashMap<String, String> errorMap = RegisterWorker.getErrorMessages(request);
				
				String errorMessage = "";
				if(ret!=SUCCESS){
					switch(ret){
						case 1:
							//duplicate username
							errorMessage = errorMap.get("10001");
							break;
						case 2:
							//duplicate org
							errorMessage = errorMap.get("10002");
							break;
						case 3:
							//duplicate email
							errorMessage = errorMap.get("10003");
							break;
					}
					
					request.setAttribute("errorExist", errorMessage);
					RequestDispatcher rd = request.getRequestDispatcher("/orgadmin/account_management.jsf?page=register");
					rd.forward(request, response);
					
				} else {
					request.setAttribute("firstName",register.getFirstName());
					request.setAttribute("surName",register.getSurName());
					request.setAttribute("email",register.getEmail());
					
					
					if (register.isAdmin() && StringUtil.isNotEmpty(register.getOrg())){
				    	request.setAttribute("orgNameForIpEntry",register.getOrg());	
				    	//req.setAttribute("memberId",vo.getAthensId());//this is actually the memberID	
				    }
					
					//loginUser(request,response,register);
					RequestDispatcher rd = request.getRequestDispatcher("/orgadmin/account_management.jsf?page=reg_success");
					rd.forward(request, response);
				}
				
				LOGGER.info("REG");		
			} else {
				response.sendRedirect("/orgadmin/account_management.jsf?page=register");
			}
		} else {
			LOGGER.info("redirect");
		}
	}

	private void loginUser(HttpServletRequest request, HttpServletResponse response, Register register) {
		LOGGER.info("==loginUser");
		String username = register.getUserName();
		String password = UnixCrypt.crypt(register.getPassWord());
		OrganisationWorker.trackOrganisationLogin( request.getSession(false));
		
		LOGGER.info(" -------------------------------------------  Start User login  " );
		User user = LoginServlet.findUserStatic(username, password);
		
		if(StringUtils.isNotEmpty(user.getUsername())) {
			LOGGER.info(" -------------------------------------------  Found user  " + user.getUsername() ); 
			HttpSession session = request.getSession();
			//UserWorker.setUserInSession( session , user );
			UserWorker.recordLoginTime(session);
			LOGGER.info(" ------------------------------------------- " + user.getUsername() + " has logged in" );
			
			LOGGER.info(" ------------------------------------------- BEGIN ConfirmationBean.setDateTermsUpdated" );
			ConfirmationBean.setDateTermsUpdated(session,username,password);
			
			
			//required for seperating Ebooks login from CJO Login
			CJOLoginBean.setEncryptedDetails(request, user.getEncryptedDetails());
			
			//this is required for mulitple login to logout successfully	
			RelogBean.saveLogin(request, RelogBean.MAIN);
			
			//required for sign-up trial link. checks if has subscription
			(new SubscriptionBean()).setSubscription(request);
									
			//for login in login
			InternalReportsWorker.listenEvent(request, response);
			
			//required to recheck free trial on login
			FreeTrialBean.recheckFreeTrial(session);
		}
		
	}

	private Register setRegister(HttpServletRequest request) {
		Register reg = new Register();
		reg.setFirstName(request.getParameter("firstName"));
		reg.setSurName(request.getParameter("surName"));
		reg.setOrg(request.getParameter("organisation"));
		reg.setAdmin("on".equals(request.getParameter("admin")));
		reg.setAddress(request.getParameter("admin"));
		reg.setCountry(request.getParameter("country"));
		reg.setState(request.getParameter("state"));
		reg.setCity(request.getParameter("city"));
		reg.setPostCode(request.getParameter("postCode"));
		reg.setAddress(request.getParameter("address"));
		reg.setAddress2(request.getParameter("address2"));
		reg.setTelephone(request.getParameter("telephone"));
		reg.setUserName(request.getParameter("userName"));
		reg.setPassWord(request.getParameter("passWord"));
		reg.setEmail(request.getParameter("email"));
		reg.setQuestion(request.getParameter("question"));
		reg.setAcceptTerms("on".equals(request.getParameter("acceptTerms")));
		reg.setEmailList("on".equals(request.getParameter("emailList")));
		reg.setThirdParty("on".equals(request.getParameter("thirdParty")));
	
		return reg;
	}
}

src/ONLINE/WebContent/orgadmin/components/account_management/account_management_js.jsp
<%@ taglib uri="/WEB-INF/lib/online.tld" prefix="o" %>
<o:url var="current_dns" option="current_dns" />

<input type="hidden" id=current_dns value="${current_dns}" />
<input type="hidden" id="page" value="${param.page}" />

<script type="text/javascript" src="${pageContext.request.contextPath}/orgadmin/js/account_management.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery/jquery.validate.min.js" ></script>

src/ONLINE/WebContent/orgadmin/components/account_management/manage_content_alerts.jsp
<%@ taglib uri="/WEB-INF/lib/c.tld" prefix="c" %>
<%@ page isELIgnored="false"%>



${contentAlertBean.initialize}
<c:set var="setting" value="${contentAlertBean.subjectSetting }" />
<h1>Manage Content Alerts</h1>



<form  id="manageContentAlertsForm" name="manageContentAlertsForm" action="/manageContentAlerts" method="post">
	<div id="registered">
		<h2>Set Alert Preferences</h2>
		
		<div id="body">
			<table cellspacing="0" class="terms">
				<tbody>
					<tr>
						<td class="check">
							<c:choose>
								<c:when test="${setting.alertType eq 1 }">
									<input type="radio" name="type" value="1" checked/>
								</c:when>
								<c:otherwise>
									<input type="radio" name="type" value="1" />
								</c:otherwise>
							</c:choose>
						</td>
						<th class="fields">
							<label for="1">Send me an email alert whenever any books in the selected subject areas below are published online.</label>
						</th>
					</tr>			
					<tr>
						<td class="check">
							<c:choose>
								<c:when test="${setting.alertType eq 0 }">
									<input type="radio" name="type" value="0" checked/>
								</c:when>
								<c:otherwise>
									<input type="radio" name="type" value="0" />
								</c:otherwise>
							</c:choose>
						</td>
						<th class="fields">
							<label for="0">Unsubscribe from all email alerts for all subject areas. <br/> (If you wish to unsubscribe only from alerts for some subject areas, please un-tick the boxes below for individual subject areas as needed.)</label>	
						</th>
					</tr>
				</tbody>
			</table>
			<input type="hidden" name="emailFormat" value="${setting.emailFormat }" />
			<table cellspacing="0" class="registered_buttons">
				<tr>
					<td>
						<input type="reset" class="button" value="Reset" />
						<input type="submit" class="button" name="UpdatePreferences" value="Update"/>
					</td>
				</tr>
			</table>
		</div>		
	</div>
	<br/>
	
	<div id="registered">
		<div id="searchresults">
			<a name="top"></a>
				<table cellspacing="0">
					<tr class="shaded">
					  <th class="title" scope="col">Select Subject Area(s)</th>
					  <th scope="col">&nbsp;</th>
					  <th scope="col">&nbsp;</th>
					</tr>
				</table>
			<c:set var="count" value="0"/>
			<table cellspacing="0">
				<c:forEach var="subject" items="${contentAlertBean.subjectHierarchy}" varStatus="index">
					<c:choose>
						<c:when test="${subject.subjectLevel eq 1}">
							<tr class="shaded">
						  		<th class="title" scope="col">${subject.subjectName}</th>
	 	  					    <th scope="col">
						  			<c:if test="${subject.withAlert eq 'Y'}">
										<input id="${subject.subjectId}:${subject.subjectLevel}" type="checkbox" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" checked="checked" />
									</c:if>		 	  					    
						  			<c:if test="${subject.withAlert eq 'N'}">
										<input id="${subject.subjectId}:${subject.subjectLevel}" type="checkbox" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" />
									</c:if>	
	 	  					    </th>
							</tr>
						</c:when>
						<c:when test="${(subject.subjectLevel eq 2)}">
							<tr class="shaded">
						  		<td class="title">
						  			<c:forEach begin="1" end="${subject.subjectLevel}">
										&nbsp;
									</c:forEach>
									<b>${subject.subjectName}</b>
						  		</td>
						  		<td align="right">
						  			<c:if test="${subject.withAlert eq 'Y'}">
										<input id="${subject.subjectId}:${subject.subjectLevel}" type="checkbox" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" checked="checked"  />
									</c:if>					  		
						  			<c:if test="${subject.withAlert eq 'N'}">
										<input id="${subject.subjectId}:${subject.subjectLevel}" type="checkbox" name="parentSubject" value="${subject.subjectId}" title="${subject.path}"  />
									</c:if>							  		
						  		</td>
							</tr>
							<c:if test="${(subject.subjectLevel < contentAlertBean.subjectHierarchy[index.count-2].subjectLevel) and (subject.subjectLevel eq contentAlertBean.subjectHierarchy[index.count].subjectLevel)}">
								<tr>
									<td align="right">&nbsp;</td>
									<td align="right"><a href="#top">back to top</a></td>
								</tr>
							</c:if>
							<c:if test="${(contentAlertBean.subjectHierarchy[index.count].subjectLevel eq 1)}">
								<tr>
									<td align="right">&nbsp;</td>
									<td align="right"><a href="#top">back to top</a></td>
								</tr>
							</c:if>
						</c:when>
						<c:when test="${(subject.subjectLevel gt 2) and (subject.subjectLevel < contentAlertBean.subjectHierarchy[index.count].subjectLevel)}">
							<tr class="shaded">
						  		<td class="title">
						  			<c:forEach begin="1" end="${subject.subjectLevel + 4}">
										&nbsp;
									</c:forEach>
									<b>${subject.subjectName}</b>
						  		</td>
						  		<td align="right">
						  			<c:if test="${subject.withAlert eq 'Y'}">
										<input id="${subject.subjectId}:${subject.subjectLevel}" type="checkbox" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" checked="checked" />
									</c:if>
						  			<c:if test="${subject.withAlert eq 'N'}">
										<input id="${subject.subjectId}:${subject.subjectLevel}" type="checkbox" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" />
									</c:if>					  		
						  		</td>
							</tr>
						</c:when>					
						<c:when test="${subject.subjectLevel > manageContentAlertsForm.subjectHierarchy[index.count].subjectLevel}">
							<tr>
								<td align="right">
									<c:forEach begin="1" end="${subject.subjectLevel + 7}">
										&nbsp;
									</c:forEach>
									${subject.subjectName} 
								</td>
								<td align="right">
									<c:if test="${subject.withAlert eq 'Y'}">
										<input type="checkbox" id="${subject.subjectId}:${subject.subjectLevel}" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" checked="checked" />								
									</c:if>
									<c:if test="${subject.withAlert eq 'N'}">
										<input type="checkbox" id="${subject.subjectId}:${subject.subjectLevel}" name="parentSubject" value="${subject.subjectId}" title="${subject.path}"/>								
									</c:if>
								</td>
							</tr>						
							<tr>
								<td align="right">&nbsp;</td>
								<td align="right"><a href="#top">back to top</a></td>
							</tr>
						</c:when>		
						<c:otherwise>
							<tr>
								<td align="right">
									<c:forEach begin="1" end="${subject.subjectLevel + 7}">
										&nbsp;
									</c:forEach>
									${subject.subjectName}
								</td>
								<td align="right">
									<c:if test="${subject.withAlert eq 'Y'}">
										<input type="checkbox" id="${subject.subjectId}:${subject.subjectLevel}" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" checked="checked" />
										
									</c:if>
									<c:if test="${subject.withAlert eq 'N'}">
										<input type="checkbox" id="${subject.subjectId}:${subject.subjectLevel}" name="parentSubject" value="${subject.subjectId}" title="${subject.path}" />
									</c:if>
								</td>
							</tr>					
						</c:otherwise>
					</c:choose>
				</c:forEach>
				<tr>
					<td align="right">&nbsp;</td>
					<td align="right"><a href="#top">back to top</a></td>
				</tr>
			</table>
			<table cellspacing="0" class="registered_buttons">
				<tr>
					<td>
						<input type="reset" class="button" value="Reset" />
						<input type="submit" class="button" name="UpdateSubjectAlert" value="Update"  />
					</td>
				</tr>
			</table>
		</div>
	</div>	
</form>
<script language="JavaScript" type="text/Javascript">




	function removeFromArray(array, item){
		var arr = array;
		var removeItem = item; // item to remove from array
		
		return jQuery.grep(arr, function(value) {
			return value != removeItem;
		});
	}

	function toggle(checkbox){	
		var checked = checkbox.attr('checked') == true ? true : false;
		var id = checkbox.attr('id').split(':')[0];
		var level = checkbox.attr('id').split(':')[1];
		var parent = checkbox.attr('title').split(':')[level-1];


		for(x=0; x<(document.manageContentAlertsForm.getElementsByTagName('input').length); x++)
		{
		
			var currentPath = document.manageContentAlertsForm.getElementsByTagName('input')[x].getAttribute('title');
			if(currentPath != null)
				if(currentPath.split(':')[level] == id)
					document.manageContentAlertsForm.getElementsByTagName('input')[x].checked = checked;
					
		}
		
		var parentIds = checkbox.attr('title').split(':');
		if(checked == true)
		{
			for(p=parentIds.length-2; p>0; p--)
			{
			
				var lengthOfChildCheckboxes = $("input[title*=':" + parentIds[p] + ":']").length;
				var lengthOfSelectedChildCheckboxes = $("input[title*=':" + parentIds[p] + ":']:checked").length
				if(lengthOfChildCheckboxes == lengthOfSelectedChildCheckboxes)
				{
					$("input[id^='" + parentIds[p] + ":']").attr('checked', true);
				}
			}			
		}
		else
		{
			for(p=1; p<parentIds.length-1; p++)
				$("input[id^='" + parentIds[p] + ":']").attr('checked', false);
		}	
	}


//-->
</script>
