src/ONLINE/src-web/org/cambridge/ebooks/online/faq/FaqSubjectAreaDetailsBooksBean.java
package org.cambridge.ebooks.online.faq;

import java.util.Date;

/**
 * @author Karlson A. Mulingtapang
 * FaqSubjectAreaDetailsBooksBean.java - FaqSubjectAreaDetailsBooks
 */
public class FaqSubjectAreaDetailsBooksBean {
	private int id;
	private String question;
	private String answer;
	private int displayOrder;	
	private String enable;
	private Date modifiedDate;
	private String modifiedBy;
	
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return the question
	 */
	public String getQuestion() {
		return question;
	}
	/**
	 * @param question the question to set
	 */
	public void setQuestion(String question) {
		this.question = question;
	}
	/**
	 * @return the answer
	 */
	public String getAnswer() {
		return answer;
	}
	/**
	 * @param answer the answer to set
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}
	/**
	 * @return the displayOrder
	 */
	public int getDisplayOrder() {
		return displayOrder;
	}
	/**
	 * @param displayOrder the displayOrder to set
	 */
	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}
	/**
	 * @return the enable
	 */
	public String getEnable() {
		return enable;
	}
	/**
	 * @param enable the enable to set
	 */
	public void setEnable(String enable) {
		this.enable = enable;
	}
	/**
	 * @return the modifiedDate
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}
	/**
	 * @param modifiedDate the modifiedDate to set
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	/**
	 * @return the modifiedBy
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}
	/**
	 * @param modifiedBy the modifiedBy to set
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
}

src/ONLINE/src-web/org/cambridge/ebooks/online/faq/FaqSubjectAreaTypeBooksBean.java
package org.cambridge.ebooks.online.faq;

import java.util.Date;
import java.util.List;

/**
 * @author Karlson A. Mulingtapang
 * FaqSubjectAreaTypeBooksBean.java - FaqSubjectAreaTypeBooks Bean
 */
public class FaqSubjectAreaTypeBooksBean {
	
	private int id;
	private String subjectAreaType;
	private String subjectAreaDescription;
	private int displayOrder;
	private String enable;
	private Date modifiedDate;
	private String modifiedBy;
	private int languageCode;
	
	
	private List<FaqSubjectAreaDetailsBooksBean> faqSubjectAreaDetailsBooksBeans;
	
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return the subjectAreaType
	 */
	public String getSubjectAreaType() {
		return subjectAreaType;
	}
	/**
	 * @param subjectAreaType the subjectAreaType to set
	 */
	public void setSubjectAreaType(String subjectAreaType) {
		this.subjectAreaType = subjectAreaType;
	}
	/**
	 * @return the subjectAreaDescription
	 */
	public String getSubjectAreaDescription() {
		return subjectAreaDescription;
	}
	/**
	 * @param subjectAreaDescription the subjectAreaDescription to set
	 */
	public void setSubjectAreaDescription(String subjectAreaDescription) {
		this.subjectAreaDescription = subjectAreaDescription;
	}
	/**
	 * @return the displayOrder
	 */
	public int getDisplayOrder() {
		return displayOrder;
	}
	/**
	 * @param displayOrder the displayOrder to set
	 */
	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}
	/**
	 * @return the enable
	 */
	public String getEnable() {
		return enable;
	}
	/**
	 * @param enable the enable to set
	 */
	public void setEnable(String enable) {
		this.enable = enable;
	}
	/**
	 * @return the modifiedDate
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}
	/**
	 * @param modifiedDate the modifiedDate to set
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	/**
	 * @return the modifiedBy
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}
	/**
	 * @param modifiedBy the modifiedBy to set
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	/**
	 * @return the faqSubjectAreaDetailsBooksBeans
	 */

	public List<FaqSubjectAreaDetailsBooksBean> getFaqSubjectAreaDetailsBooksBeans() {
		return faqSubjectAreaDetailsBooksBeans;
	}
	/**
	 * @param faqSubjectAreaDetailsBooksBeans the faqSubjectAreaDetailsBooksBeans to set
	 */
	public void setFaqSubjectAreaDetailsBooksBeans(
			List<FaqSubjectAreaDetailsBooksBean> faqSubjectAreaDetailsBooksBeans) {
		this.faqSubjectAreaDetailsBooksBeans = faqSubjectAreaDetailsBooksBeans;
	}
	
	public void setLanguageCode(int languageCode) {
		this.languageCode = languageCode;
	}
	public int getLanguageCode() {
		return languageCode;
	}


}

src/ONLINE/src-web/org/cambridge/ebooks/online/faq/FaqSubjectTypeDetailsMapBooksBean.java
package org.cambridge.ebooks.online.faq;


/**
 * @author Karlson A. Mulingtapang
 * FaqSubjectTypeDetailsMapBooksBean.java - FaqSubjectTypeDetailsMapBooks Bean
 */
public class FaqSubjectTypeDetailsMapBooksBean {
	
	private int faqSubjectAreaTypeId;
	private int faqSubjectAreaDetailsId;
	
	private FaqSubjectAreaTypeBooksBean faqSubjectAreaTypeBooksBean;
	private FaqSubjectAreaDetailsBooksBean faqSubjectAreaDetailsBooksBean;
	
	/**
	 * @return the faqSubjectAreaTypeId
	 */
	public int getFaqSubjectAreaTypeId() {
		return faqSubjectAreaTypeId;
	}
	/**
	 * @param faqSubjectAreaTypeId the faqSubjectAreaTypeId to set
	 */
	public void setFaqSubjectAreaTypeId(int faqSubjectAreaTypeId) {
		this.faqSubjectAreaTypeId = faqSubjectAreaTypeId;
	}
	/**
	 * @return the faqSubjectAreaDetailsId
	 */
	public int getFaqSubjectAreaDetailsId() {
		return faqSubjectAreaDetailsId;
	}
	/**
	 * @param faqSubjectAreaDetailsId the faqSubjectAreaDetailsId to set
	 */
	public void setFaqSubjectAreaDetailsId(int faqSubjectAreaDetailsId) {
		this.faqSubjectAreaDetailsId = faqSubjectAreaDetailsId;
	}
	/**
	 * @return the faqSubjectAreaTypeBooksBean
	 */
	public FaqSubjectAreaTypeBooksBean getFaqSubjectAreaTypeBooksBean() {
		return faqSubjectAreaTypeBooksBean;
	}
	/**
	 * @param faqSubjectAreaTypeBooksBean the faqSubjectAreaTypeBooksBean to set
	 */
	public void setFaqSubjectAreaTypeBooksBean(
			FaqSubjectAreaTypeBooksBean faqSubjectAreaTypeBooksBean) {
		this.faqSubjectAreaTypeBooksBean = faqSubjectAreaTypeBooksBean;
	}
	/**
	 * @return the faqSubjectAreaDetailsBooksBean
	 */
	public FaqSubjectAreaDetailsBooksBean getFaqSubjectAreaDetailsBooksBean() {
		return faqSubjectAreaDetailsBooksBean;
	}
	/**
	 * @param faqSubjectAreaDetailsBooksBean the faqSubjectAreaDetailsBooksBean to set
	 */
	public void setFaqSubjectAreaDetailsBooksBean(
			FaqSubjectAreaDetailsBooksBean faqSubjectAreaDetailsBooksBean) {
		this.faqSubjectAreaDetailsBooksBean = faqSubjectAreaDetailsBooksBean;
	}
}

src/ONLINE/src-web/org/cambridge/ebooks/online/help/ViewAccessDetailsBean.java
package org.cambridge.ebooks.online.help;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.dto.viewaccess.OrganisationDetails;
import org.cambridge.ebooks.online.jpa.organisation.Organisation;
import org.cambridge.ebooks.online.jpa.user.User;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.ebooks.online.user.UserWorker;
import org.cambridge.ebooks.online.util.HttpUtil;
import org.cambridge.ebooks.online.util.MailManager;
import org.cambridge.ebooks.online.util.StringUtil;

/**
 * @author Karlson A. Mulingtapang 
 * ViewAccessDetailsBean.java - Access Details
 */
public class ViewAccessDetailsBean {
	
	private static final Logger LOGGER = Logger.getLogger(ViewAccessDetailsBean.class);
	
	private static final String NONE = "none";
	
	private static final String[] EMAIL_ADMIN_BCC 
		= new String[] {System.getProperty("email.admin").trim(), System.getProperty("email.admin.bcc").trim()};	
	private static final String TEMPLATE_DIR 
		= System.getProperty("templates.dir").trim();
	private static final String TEMPLATE_FILE 
		= System.getProperty("mail.user.info.template").trim();
	private static final String OUTPUT_DIR = System.getProperty("mail.store.path").trim();

	private String userId;
	private String bodyId;
	private String sessionId;
	private String fullName;
	private String emailAddress;

	private String userEmailAddress;
	private String emailSubject = "Cambridge Books Online";
	private String typeOfProblem;
	private String problemDescription;
	private String location;
	
	private final String usEmail = System.getProperty("view.access.email.us").trim();
	private final String ukEmail = System.getProperty("view.access.email.uk").trim();
	public static final String DO_NOT_REPLY_EMAIL = System.getProperty("do.not.reply.email").trim();
	
	private final User user = UserWorker.getUserInfoInSession(HttpUtil.getHttpSession(false));

	private Map<String, String> consortiaInSession = new LinkedHashMap<String, String>();
	private Map<String, String> societyInSession = new LinkedHashMap<String, String>();
	private Map<String, String> offerInSession = new LinkedHashMap<String, String>();
	
	private List<OrganisationDetails> organisationDetailsInSession = new ArrayList<OrganisationDetails>();

	public ViewAccessDetailsBean() {
		
	}

	public String getUserId() {
		if(this.user != null){
			this.userId = this.user.getUsername();
			if(StringUtils.isEmpty(this.userId)) {
				return NONE;
			}
			LOGGER.info("getUserId(): " + this.userId);
		} else {
			return NONE;
		}
		
		return this.userId;
	}

	public String getBodyId() {
		if(this.user != null){
			this.bodyId = this.user.getBodyId();
			if(StringUtils.isEmpty(this.bodyId)) {
				return NONE;
			}
			LOGGER.info("getBodyId(): " + this.bodyId);
		} else {
			return NONE;
		}	
		
		return this.bodyId;
	}

	public String getSessionId() {
		HttpSession session = HttpUtil.getHttpSession(false);
		if (session != null) {
			this.sessionId = session.getId();
		}

		return this.sessionId;
	}    

	public String getFullName() {
		if(this.user != null){
			this.fullName = user.getFirstName() + " " + user.getLastName();
			LOGGER.info("getFullName(): " + this.fullName);
		} else {
			return NONE;
		}
		return this.fullName;
	}

	public String getEmailAddress() {
		if(this.user != null){
			this.emailAddress = this.user.getEmail();
			if(StringUtils.isEmpty(this.emailAddress)) {
				return NONE;
			}
			LOGGER.info("getEmailAddress(): " + this.emailAddress);
		} else {
			return NONE;
		}
		return this.emailAddress;
	}

	public String sendEmail(){
		FacesContext context = FacesContext.getCurrentInstance();
		String recipient = "";
		String location = "";
		try {
						
			StringBuilder body = new StringBuilder();			
			
			if(StringUtil.isNotEmpty(this.getTypeOfProblem())){
				body.append("<b>Predefined Problem:</b> " + this.getTypeOfProblem() + "<br>");
			}
			
			body.append("<b>Describe Your Problem:</b> " + this.getProblemDescription() + "<br>");
			
			body.append("<b>Reported by:</b> " + this.getUserEmailAddress() + "<br>");
			
			if(StringUtil.isNotEmpty(this.getLocation())){
				recipient = this.getLocation().trim().split(":")[0];
				location = this.getLocation().trim().split(":")[1];
				
				body.append("<b>Location:</b> " + location);
			}
			body.append(this.getAccessDetails());
			MailManager.storeMail(TEMPLATE_DIR, 
								  TEMPLATE_FILE, 
								  OUTPUT_DIR, 
								  DO_NOT_REPLY_EMAIL, 
								  new String[]{recipient}, 
								  null, 
								  EMAIL_ADMIN_BCC, 
								  this.getEmailSubject(), 
								  body.toString());
			
			FacesMessage message = new FacesMessage("Your e-mail has been sent.");
			context.addMessage("emailMessage", message);			
			
		} catch (Exception e) {
			LOGGER.info("[Exception] " + e.getMessage());
			FacesMessage message = new FacesMessage("Your e-mail has not been sent. Please try again.");
			context.addMessage("emailMessage", message);
		} finally {
			this.reset();
		}
		
		return "view_access_details";
	}
	
	
	public List<OrganisationDetails> getOrganisationInSession() {
		if (this.organisationDetailsInSession == null
				|| this.organisationDetailsInSession.isEmpty()) {

			List<OrganisationDetails> orgDetailsList = new ArrayList<OrganisationDetails>();
			
			OrgConLinkedMap map = OrgConLinkedMap.getFromSession(HttpUtil.getHttpServletRequest());
			List<Organisation> orgList = map.getAllOrganisation();
			
			for(Organisation org : orgList){
				OrganisationDetails orgDetails = new OrganisationDetails();
				orgDetails.setBodyId(org.getBodyId());
				orgDetails.setDisplayName(org.getBaseProperty(Organisation.DISPLAY_NAME));
				orgDetails.setMessageText(org.getBaseProperty(Organisation.MESSAGE_TEXT));
				
				orgDetailsList.add(orgDetails);				
			}		

			this.organisationDetailsInSession = orgDetailsList;
		}
		return organisationDetailsInSession;
	}
	
	public Map<String, String> getConsortiaInSession() {
		if (this.consortiaInSession == null
				|| this.consortiaInSession.isEmpty()) {

			Map<String, String> result = new LinkedHashMap<String, String>();
			
			OrgConLinkedMap map = OrgConLinkedMap.getFromSession(HttpUtil.getHttpServletRequest());
			List<Organisation> orgList = map.getAllConsortium();
			for(Organisation org : orgList){
				result.put(org.getBodyId(), org.getBaseProperty(Organisation.DISPLAY_NAME));
			}			
			
			if(result.isEmpty()){
				result.put(NONE, NONE);
			}
						

			this.consortiaInSession = result;
		}
		return consortiaInSession;
	}	
	
	public Map<String, String> getSocietyInSession() {
		if (this.societyInSession == null
				|| this.societyInSession.isEmpty()) {

			Map<String, String> result = new LinkedHashMap<String, String>();
			
			OrgConLinkedMap map = OrgConLinkedMap.getFromSession(HttpUtil.getHttpServletRequest());
			List<Organisation> orgList = map.getAllSociety();
			for(Organisation org : orgList){
				result.put(org.getBodyId(), org.getBaseProperty(Organisation.DISPLAY_NAME));
			}
			
			if(result.isEmpty()){
				result.put(NONE, NONE);
			}

			this.societyInSession = result;
		}
		return societyInSession;
	}
	
	public Map<String, String> getOfferInSession() {
		if (this.offerInSession == null
				|| this.offerInSession.isEmpty()) {

			Map<String, String> result = new LinkedHashMap<String, String>();
			
			result.put(NONE, NONE);			

			this.offerInSession = result;
		}
		return offerInSession;
	}

	public void reset() {
		this.userEmailAddress = "";
		this.emailSubject = "";
		this.typeOfProblem = "";
		this.problemDescription = "";
		this.location = "";
	}

	public void validateEmail(FacesContext context, UIComponent component,
			Object value) throws ValidatorException {

		if(value != null) {
			if(!(value instanceof String)) {
				throw new ValidatorException(new FacesMessage("The value must be a String."));
			}
			
			String email = (String) value;
			
			if (email.indexOf("@") < 0) {
				throw new ValidatorException(new FacesMessage("Invalid Email Address."));  
			}
		}
	}
	
	public static final String BR = "<br/>";
	
	
	
	public String getAccessDetails() throws UnknownHostException{	
		HttpServletRequest request = HttpUtil.getHttpServletRequest();
		StringBuffer sb = new StringBuffer();
		sb.append("<h1>View Access Details</h1>");
		sb.append("<p>Below is a summary of your user details. You may use this information in order to work with your local administrator to troubleshoot any access issues you have, or you can contact Cambridge University Press Customer Services by filling in the form below and submitting it.</p>");
		sb.append("<h2>User Details</h2>");		
		sb.append("<p>Browser & OS: " + getBrowser() + "</p>" );
		sb.append("<p>IP Address: " + getIPAdress() + "</p>");
		sb.append("<p>Domain Name: " + request.getRemoteHost() + "</p>");
		sb.append("<p>Node: " + InetAddress.getLocalHost().getHostName() + "</p>");
		sb.append("<p>Body Id: " + this.getBodyId() + "</p>");
		sb.append("<p>Session Id: " + this.getSessionId() + "</p>");
		sb.append("<p>User&#8217;s Full Name: " + this.getFullName() + "</p>");
		sb.append("Email Address: " + this.getEmailAddress() + "</p>");
		sb.append("<h2>Organisation Details</h2>");		
		sb.append(getOrgList());	
		sb.append("<h2>Consortia Details</h2>");
		sb.append(getConsortiaList());
		sb.append("<h2>Society Details</h2>");
		sb.append(getSocietyList());
		sb.append("<h2>Offer Details</h2>");
		sb.append(getOfferList());		
		return sb.toString();
	}
	

src/ONLINE/WebContent/popups/common_css.jsp
<link href="${pageContext.request.contextPath}/css/popup.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />

src/ONLINE/WebContent/popups/footer.jsp
<div id="footer">
<div class="copyright">
  <ul>
        	<li>&copy; Cambridge University Press <script type="text/javascript" language="JavaScript"><!--
var today = new Date();
document.write(today.getFullYear());
//--></script>.</li>
			<li><a href="${pageContext.request.contextPath}/about.jsf" target="_blank">About Cambridge Books Online</a></li>
            <li><a href="${pageContext.request.contextPath}/contact.jsf" target="_blank">Contact Us</a></li>
            <li><a href="${pageContext.request.contextPath}/accessibility.jsf" target="_blank">Accessibility</a></li>
            <li><a href="${pageContext.request.contextPath}/terms_of_use.jsf" target="_blank">Terms of Use</a></li>
            <li><a href="${pageContext.request.contextPath}/privacy_policy.jsf" target="_blank">Privacy Policy</a></li>
            <li><a href="${pageContext.request.contextPath}/rights_and_permissions.jsf" target="_blank">Rights &amp; Permission</a></li>
            <li><a href="${pageContext.request.contextPath}/sitemap.jsf" target="_blank">Site Map</a></li>
        </ul>
    </div>
</div>

src/ONLINE/WebContent/popups/recommendToLibrarian.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="/WEB-INF/lib/c.tld" prefix="c" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>	
<%@page import="org.cambridge.ebooks.online.email.RecommendToLibrarianBean"%>
<%@page import="org.cambridge.ebooks.online.email.Email"%>
<%@page import="org.cambridge.ebooks.online.jpa.user.User"%>

<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">

<f:view>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Cambridge Books Online - Cambridge University Press</title>
	<f:subview id="commonCssSubview">
		<c:import url="/popups/common_css.jsp" />
	</f:subview>	
</head>

<body>

<h:form id="recommendForm" prependId="false"> 

<div class="content" style="height: 430px;">	
	<input type="hidden" name="bid" value="${param.bid}" />
	
	<h:panelGroup rendered="#{!recommendToLibrarian.displayDetails}">
	<ul>
    	<li class="header">Recommend This to a Librarian</li>
    	<li><font color="#FF0000"><h:messages layout="list" /></font></li>
    	<li><h:commandLink value="Go Back" action="#{recommendToLibrarian.goBack}" /></li>   	
	</ul>
	</h:panelGroup>
	<h:panelGroup rendered="#{recommendToLibrarian.displayDetails}">
	<ul>
    	<li class="header">Recommend This to a Librarian</li>
    	<li>Email your librarian to recommend adding this book to the library's collection. Either send your message to the library administrator listed below (we use your IP address to fill these fields in) or enter a new email address in the Librarian email address box. You can also add a message.</li>
	</ul> 		
	
   	<font color="#FF0000"><h:messages layout="list" /></font>
   	
	<input name ="exactURL" value='${param.exactURL}' type="hidden" />
   	
    <table cellspacing="0"> 
		<tr>
            <td><label for="name">Your name:</label></td>
            <td class="fields">
            	<h:inputText id="userName" styleClass="register_field"
            		value="#{recommendToLibrarian.userName}" />
            </td>
        </tr>
        
        <tr class="border">
            <td><label for="userEmail">Your email address*:</label></td>
            <td class="fields">
	            <h:inputText id="userEmail" styleClass="register_field" 
						value="#{recommendToLibrarian.userEmail}" required="true" 
						validator="#{recommendToLibrarian.validateEmail}" maxlength="80" >
					<f:attribute name="requiredMessage" value="Email address is required"/>
				</h:inputText>
           </td>
        </tr>
        
        <!-- addition ko -->
        <%--
        <tr class="border">
            <td><label for="userOrgs">Organisations*:</label></td>
            <td class="fields">
            	<select name="organisation" id="organisations" onchange="getEmail();">
            		<option>Select an Organisation</option>>
  					<c:forEach var="organisation" items="${accessDetailsBean.organisationInSession}">
						<option value="${organisation.key}" >${organisation.value}</option>>
					</c:forEach>	
				</select>
           </td>
        </tr>
		 --%>	 
        <!-- addition ko END-->
        
        <tr class="border">
            <td><label for="recipientName">Librarian name:</label></td>

            <td>
				<h:inputText id="recipientName" styleClass="register_field" 
					value="#{recommendToLibrarian.recipientName}" />
			</td>
			<!--
			<td class="fields">
                <input name="recipientName" value="" class="register_field" id="name" type="text" />
            </td>
        	-->
        </tr>
        
		<tr class="border">
            <td><label for="recipientEmail">Librarian email address*:</label></td>
            <td>
				<h:inputText id="recipientEmail" styleClass="register_field" 
					value="#{recommendToLibrarian.recipientEmail}" required="true"
					validator="#{recommendToLibrarian.validateEmail}" maxlength="80" >
					<f:attribute name="requiredMessage" value="Recipient email address is required"/>
				</h:inputText>
			</td>
        </tr>
        
        <tr class="border">
            <td><label for="subjectEmail">Subject:</label></td>
            <td>
				<h:inputText id="subjectEmail" styleClass="register_field"  value="#{recommendToLibrarian.subject}" readonly="true" size="60"/>
			</td>
        </tr>
        
        <tr class="border">
            <td><label for="content">Message</label></td>
            <td>
            	
				<h:inputTextarea id="body" styleClass="problem" value="#{recommendToLibrarian.mailmessage}" cols="23" rows="5" required="true" >				
					<f:attribute name="requiredMessage" value="Message is required"/>
				</h:inputTextarea >				
			</td>
			
		<!--<td><textarea name="content" cols="1" rows="5" class="email" id="content"></textarea></td>-->     
        </tr>
        
	</table>

	<div id="bottomButtons">		 
		<a href="javascript:doReset();" title="Reset"><img src="${pageContext.request.contextPath}/images/bot_reset.gif" /></a>       	
       	<a href="javascript:doEmail();" title="Email"><img src="${pageContext.request.contextPath}/images/bot_email.gif" /></a>       
       	<h:commandButton id="resetBtn" type="reset" style="display: none;" />
       	<h:commandButton id="email_send" action="#{recommendToLibrarian.sendEmail}" style="display: none;" />      	
		<h:message for="email_send"/>
    </div>
	</h:panelGroup>
</div><!-- end content -->
</h:form>
<f:subview id="commonJsSubview">
	<c:import url="/popups/common_js.jsp" />
</f:subview>
<script type="text/javascript">
	function doReset() {
		$("#resetBtn").click();
	}
	
	function doEmail() {
		$("#email_send").click();
	}

	function send(formName){
		 var form = document.forms[formName];
		 form.action = form.action + "#country";
		 form.submit();
	} 
</script>
<f:subview id="googleAnalyticsSubview">
	<c:import url="/components/google_analytics.jsp" />
</f:subview>
</body>
</f:view>
</html>