src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/marcrecords/FilterMarcRecordServlet.java
package org.cambridge.ebooks.orgadmin.marcrecords;


import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.util.ExceptionPrinter;
import org.cambridge.ebooks.orgadmin.db.DBManager;


/**
 * Servlet Class
 *
 * @web.servlet              name="FilterMarcRecord"
 *                           display-name="Name for FilterMarcRecord"
 *                           description="Description for FilterMarcRecord"
 * @web.servlet-mapping      url-pattern="/FilterMarcRecord"
 * @web.servlet-init-param   name="A parameter"
 *                           value="A value"
 */
public class FilterMarcRecordServlet extends HttpServlet {	
	private static final long serialVersionUID = -4620205534618929586L;
	private static final Logger LOGGER = Logger.getLogger(FilterMarcRecordServlet.class);

	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		doPost(req, resp);
	}

	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {		
		resp.setContentType("text/plain");
		LOGGER.info("======= filterMarcrecords");
		int bodyId = 0;
		String filterType = "";
		try  {
			bodyId = Integer.parseInt(req.getParameter("bodyId"));
			filterType = req.getParameter("filterType");
			LOGGER.info("======= orderId:" + bodyId);
		} catch(Exception e) {
			e.printStackTrace();
			LOGGER.error("[doPost]:" + e.getMessage());
		}
	
		if(bodyId!=0){
			LOGGER.info(filterType);
			setOrderId(bodyId,filterType,req,resp);
		}		
	}
	
	private void setOrderId(int bodyId,String filterType, HttpServletRequest req, HttpServletResponse resp)	throws ServletException, IOException {
		//order types
		final char HAS_ACCESS = 'P'; 
		final char SUBSCRIPTION = 'S';
		final char PATRON_DRIVEN = 'M';
			
		LOGGER.info("======= filterMarcRecord by order id");
		StringBuilder filtermarcRecordsSql = new StringBuilder();
		if(bodyId==-1&&"byOrderId".equals(filterType)){
			filtermarcRecordsSql.append("select  DISTINCT(ORDER_ID) from oraebooks.EBOOKS_ACCESS_MARC_VIEW order by ORDER_ID desc");
		}
		else if (bodyId>0&&"byOrderId".equals(filterType)){
			filtermarcRecordsSql.append("select  DISTINCT(ORDER_ID) ,BODY_ID from oraebooks.EBOOKS_ACCESS_MARC_VIEW where BODY_ID = ").append(bodyId).append(" order by ORDER_ID desc");
		}
		else if (bodyId==-1&&"byDate".equals(filterType)){
			//filtermarcRecordsSql ="select DISTINCT(trunc(DATE_CREATED)) from oraebooks.EBOOK_ORDER order by trunc(date_created) where order_type = ";
			filtermarcRecordsSql.append("select DISTINCT(trunc(DATE_CREATED)) from oraebooks.EBOOK_ORDER ");
			filtermarcRecordsSql.append("where (order_type = '").append(HAS_ACCESS);
			filtermarcRecordsSql.append("' or order_type = '").append(SUBSCRIPTION);
			filtermarcRecordsSql.append("' or order_type = '").append(PATRON_DRIVEN);
			filtermarcRecordsSql.append("') order by trunc(date_created)");
		}
		else if (bodyId>0&&"byDate".equals(filterType)){
			filtermarcRecordsSql.append("select  DISTINCT(trunc(DATE_CREATED)) from oraebooks.EBOOK_ORDER ");
			filtermarcRecordsSql.append("where BODY_ID = ").append(bodyId) ;
			filtermarcRecordsSql.append(" and ");
			filtermarcRecordsSql.append("(order_type = '").append(HAS_ACCESS);
			filtermarcRecordsSql.append("' or order_type = '").append(SUBSCRIPTION);
			filtermarcRecordsSql.append("' or order_type = '").append(PATRON_DRIVEN);
			filtermarcRecordsSql.append("') order by trunc(date_created)");
		}
		Connection conn = null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		PrintWriter out = null;
		
		boolean hasRecord = false;
		try {
			LOGGER.info(filtermarcRecordsSql.toString());
			LOGGER.info(filterType);
			
			conn = DBManager.openConnection();
			
			pstmt = conn.prepareStatement(filtermarcRecordsSql.toString());
			rs = pstmt.executeQuery();
			
			ArrayList results = new ArrayList();
			while (rs.next()) {
				hasRecord=true;
				if("byOrderId".equals(filterType)){
			    	results.add(rs.getInt("ORDER_ID"));
				}
				else if("byDate".equals(filterType)){
					results.add(rs.getDate(1));
				}
			}
			
			if(!hasRecord) {
				LOGGER.info("======= has no record redirect to:" + req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr?pageId=5212&marc_record=true&error=noMarcRecords");
				//resp.sendRedirect(req.getContextPath() + "/action/ebooks/stream?pageId=5212&marc_record=true&error=noMarcRecords&errorMessage=No+MARC+Records+were+found+for+this+organisation.");
			}
			else{
				//System.out.print("orderIdlist -----" + results);
				resp.setContentType("text/plain");
				out = resp.getWriter();
				out.println(results.toString());
				out.flush();
			}
		} catch(Exception e) {
			LOGGER.error("[buildMarcRecords]:" + e.getMessage());			
			try {
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=Error: " + e.getMessage());
			} catch (Exception _e) {
				LOGGER.error("[buildMarcRecords]:" + _e.getMessage());	
			}
		}
		finally{
			try {
				DBManager.closeConnection(conn, pstmt, rs);
				if(out != null) {
					out.close();
				}
			} catch (Exception e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));
			}
		}
		
	}
	

}



src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/marcrecords/MarcRecordsBean.java
package org.cambridge.ebooks.orgadmin.marcrecords;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.jpa.organisation.Organisation;
import org.cambridge.ebooks.online.login.authentication.OrgConLinkedMap;
import org.cambridge.ebooks.online.util.HttpUtil;


public class MarcRecordsBean {
	private static Logger LOGGER = Logger.getLogger(MarcRecordsBean.class);
	public static final String ORG_MAP = "organisationMap";
	private List<Organisation> orgList;
	
	public String getInitBean(){
		LOGGER.info("Initialize...");		
//		HttpServletRequest req = HttpUtil.getHttpServletRequest();				
		
		HttpSession session = HttpUtil.getHttpSession(false);		
		//System.out.println("hello i came first");
		/*
		 * ORG_IDS and ORG_MAP are taken from OrganisationWorker.setOrganisationDisplayInSession		
		 */
		
		//get org ids
		Set<String> orgIds = OrgConLinkedMap.getAllBodyIdsAsSet(session);
		if(orgIds == null || orgIds.size() == 0){
			orgList = null;
			return "";
		}
		
		OrgConLinkedMap map = OrgConLinkedMap.getFromSession(session);
		
		//fills up selected orgs
		List<Organisation> orgList = new ArrayList<Organisation>();			
		addOrgsInSession(map, orgList);
		
		this.orgList = orgList;
		
		LOGGER.info("Finished...");	
		
		return "";
	}
	
	private void addOrgsInSession(OrgConLinkedMap map, List<Organisation> orgList){
		for(String id : map.getMap().keySet()){
			Organisation org = map.getMap().get(id);		
			Organisation _org = new Organisation();
			_org.setBodyId(org.getBodyId());
			_org.setName(org.getBaseProperty(Organisation.DISPLAY_NAME));			
			orgList.add(_org);
		}		
	}
	
	public List<Organisation> getOrgList() {
		return orgList;	
	}
	
}

src/ONLINE/src-web/org/cambridge/ebooks/orgadmin/marcrecords/MarcRecordsServlet.java
package org.cambridge.ebooks.orgadmin.marcrecords;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.cambridge.ebooks.online.util.ExceptionPrinter;
import org.cambridge.ebooks.orgadmin.db.DBManager;

public class MarcRecordsServlet extends HttpServlet {
	
	private static final long serialVersionUID = -612840838288504663L;
	private static final Logger LOGGER = Logger.getLogger(MarcRecordsServlet.class);
	private static final String ENCODING = "UTF-8";
	
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		LOGGER.info(req.getParameter("orderIds"));
		doPost(req, resp);
	}

	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
				
		int option = -1;
		String orderIds = "";
		String dateFrom = "";
		String dateTo = "";
		try  {
			String optionParam = req.getParameter("option");
			if(StringUtils.isNotEmpty(optionParam) && StringUtils.isNumeric(optionParam)) {
				option = Integer.parseInt(optionParam);
			} 
			orderIds = req.getParameter("orderIds");
			dateFrom = req.getParameter("dateFrom");
			dateTo = req.getParameter("dateTo");
			LOGGER.info("======= option:" + option);
			LOGGER.info("======= orderIds:" + orderIds);
			LOGGER.info("======= dateFrom:" + dateFrom);
			LOGGER.info(" ======= dateTo:" + dateTo);
			

		} catch(Exception e) {
			LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));
		}
		
		
		String marcFix = req.getParameter("marcFix");
		if("Y".equals(marcFix)){
			buildMarcRecordsFix(req, resp);
		}else if(-1 == option) {
			// marc record for all published books
			if(noOption(orderIds,dateFrom,dateTo)){
				buildMarcRecords(req, resp);
			}
			else{
				buildAllMarcRecords(req,resp);
				//buildMarcRecords(req, resp);
			}
		} else {
			if(noOption(orderIds,dateFrom,dateTo)){
				buildMarcRecords(option, req, resp);
			}
			else{
				buildMarcRecordsBy(option,req,resp);
			}
		}
	}
		
	private void buildMarcRecords(HttpServletRequest req, HttpServletResponse resp) {
		LOGGER.info("======= buildMarcRecords(...)");
		StringBuffer marcRecordsSql = new StringBuffer(
			"select DISTINCT(MARC_RECORD) from ORACJOC.EBOOKS_ALL_MARC_RECORDS_VIEW");
		
		
   		Connection conn = null;
   		PreparedStatement pstmt = null;
		ResultSet rs = null;
		PrintWriter writer = null;
		boolean hasRecord = false;
		try {		
			
			conn = DBManager.openConnection();
			pstmt = conn.prepareStatement(marcRecordsSql.toString());
			rs = pstmt.executeQuery();
			
			StringBuffer marcRecords = new StringBuffer();
			
			while (rs.next()) {
				hasRecord = true;
				String record = rs.getString(1);
				String _record =  new String(record.getBytes(ENCODING), ENCODING);
				
				//LogManager.info(this, "marc recordyyy = " + _record);
				marcRecords.append(_record);			
			}
			
			if(!hasRecord) {
				LOGGER.info("======= has no record redirect to:" + req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords");
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=No+MARC+Records+were+found+for+this+organisation.");
			} else {
				//LogManager.info(this, "======= marc records:" + marcRecords.toString());
				writer = getPrintWriter(resp);			
				writer.print(marcRecords.toString());
				writer.flush();
			}
		} catch(Exception e) {
			LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));	
			try {
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=Error: " + e.getMessage());
			} catch (Exception _e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(_e));
			}
		} finally {
			try {
				DBManager.closeConnection(conn, pstmt, rs);
				if(writer != null) {
					writer.close();
				}
			} catch (Exception e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));
			}
		}
	}
	
	
	private void buildMarcRecordsFix(HttpServletRequest req, HttpServletResponse resp) {
		LOGGER.info("======= buildMarcRecords(...)");
		StringBuffer marcRecordsSql = new StringBuffer(
			"select MARC_RECORD from ORACJOC.EBOOKS_ALL_MARC_RECORDS_VIEW where isbn = ?");
		
		
   		Connection conn = null;
   		PreparedStatement pstmt = null;
		ResultSet rs = null;
		PrintWriter writer = null;
		boolean hasRecord = false;
		try {		
			
			conn = DBManager.openConnection();
			pstmt = conn.prepareStatement(marcRecordsSql.toString());
			pstmt.setString(1, req.getParameter("isbn"));
			rs = pstmt.executeQuery();
			
			StringBuffer marcRecords = new StringBuffer();
			
			while (rs.next()) {
				hasRecord = true;
				String record = rs.getString(1);				
				String _record = new String(record.getBytes(ENCODING), ENCODING);
				LOGGER.info("marc recordyyy = " + _record);
				marcRecords.append(_record);				
			}
			
			if(!hasRecord) {
				LOGGER.info("======= has no record redirect to:" + req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords");
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=No+MARC+Records+were+found+for+this+organisation.");
			} else {
				LOGGER.info("======= marc records:" + marcRecords.toString());
				writer = getPrintWriter(resp);			
				writer.print(marcRecords.toString());
				writer.flush();
			}
		} catch(Exception e) {
			LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));
			try {
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=Error: " + e.getMessage());
			} catch (Exception _e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(_e));
			}
		} finally {		
			
			try {
				DBManager.closeConnection(conn, pstmt, rs);
				if(writer != null) {
					writer.close();
				}
			} catch (Exception e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));
			}
			
		}
	}
	
	private void buildMarcRecords(int orgBodyId, HttpServletRequest req, HttpServletResponse resp) {
		LOGGER.info("======= buildMarcRecords(...)");
		StringBuffer marcRecordsSql = new StringBuffer(
			"select DISTINCT MARC_RECORD from oraebooks.EBOOKS_ACCESS_MARC_VIEW where BODY_ID = ?");
		
		
   		Connection conn = null;
   		PreparedStatement pstmt = null;
		ResultSet rs = null;
		PrintWriter writer = null;
		boolean hasRecord = false;
		try {		
			
			conn = DBManager.openConnection();
			pstmt = conn.prepareStatement(marcRecordsSql.toString());
			pstmt.setInt(1, orgBodyId);
			rs = pstmt.executeQuery();
			
			StringBuffer marcRecords = new StringBuffer();
			while (rs.next()) {
				hasRecord = true;
				String record = rs.getString(1);
				String _record = new String(record.getBytes(ENCODING), ENCODING);
				//LogManager.info(this, "marc recordyyy = " + _record);
				marcRecords.append(_record);			
			}
			
			if(!hasRecord) {
				LOGGER.info("======= has no record redirect to:" + req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords");
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=No+MARC+Records+were+found+for+this+organisation.");
			} else {
				//LogManager.info(this, "======= marc records:" + marcRecords.toString());
				writer = getPrintWriter(resp);			
				writer.print(marcRecords.toString());
				writer.flush();
			}
		} catch(Exception e) {
			LOGGER.error("[buildMarcRecords]:" + e.getMessage());			
			try {
				resp.sendRedirect(req.getContextPath() + "/orgadmin/for_librarians.jsf?page=mr&marc_record=true&error=noMarcRecords&errorMessage=Error: " + e.getMessage());
			} catch (Exception _e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(_e));
			}
		} finally {		
			try {
				DBManager.closeConnection(conn, pstmt, rs);
				if(writer != null) {
					writer.close();
				}
			} catch (Exception e) {
				LOGGER.error(ExceptionPrinter.getStackTraceAsString(e));
			}
			
		}
	}

	private void buildAllMarcRecords(HttpServletRequest req, HttpServletResponse resp) {
		LOGGER.info("======= buildAllMarcRecords(...)");
		StringBuffer marcRecordsSql = new StringBuffer();
		String orderId = "";
		String dateFrom = "";
		String dateTo = "";
		marcRecordsSql.append("select DISTINCT mv.MARC_RECORD from oraebooks.ebooks_access_marc_view mv,oraebooks.ebook_order o where ");
		marcRecordsSql.append("mv.body_id = o.body_id and ");
		LOGGER.info(marcRecordsSql.toString());
		if(!"".equals(req.getParameter("orderIds"))&&req.getParameter("orderIds")!=null ){
			orderId = req.getParameter("orderIds");
			marcRecordsSql.append("(mv.ORDER_ID = " + orderId + ") ");
		}
		if(!"".equals(req.getParameter("dateFrom"))&&req.getParameter("dateFrom")!=null){
			if(!"".equals(req.getParameter("orderIds"))&&req.getParameter("orderIds")!=null ){
				marcRecordsSql.append("OR ");
			}
			dateFrom = getConvertDate(req.getParameter("dateFrom"));
		}
		if(!"".equals(req.getParameter("dateTo"))&&req.getParameter("dateTo")!=null){
			dateTo = getConvertDate(req.getParameter("dateTo"));		

src/ONLINE/WebContent/orgadmin/components/librarians/add_widget.jsp
<%@ taglib uri="/WEB-INF/lib/c.tld" prefix="c" %>
<%@ taglib uri="/WEB-INF/lib/fn.tld" prefix="fn"%>

<div class="titlepage_admin">
	<h1>Add <em>Cambridge Books Online</em> Widget to Your Website</h1>
</div>	
<div class="titlepage_admin">
	<h1>Cambridge Books Online Quick Search</h1>
</div>

<jsp:include page="/orgadmin/components/librarians/widget_search_box.jsp" />

<br/>

<c:import url="/orgadmin/components/librarians/widget_code_inline.jsp" var="cimprt_quick" />

<c:set var="trim_qsearch" value="${fn:trim(cimprt_quick)}"/>
		
<table cellspacing="0" cellpadding="0" style="width: 100px;">
	<tbody>
		<tr>
			<td>
				<p>Copy the code from the text below:</p>
				<textarea cols="44" rows="5" name="widgetCode_qsearch" id="widget_code_textarea" readonly="readonly">${trim_qsearch}</textarea>
			</td>
		</tr>
		<tr>
			<td>
				<div class="form_button fr">
					<span>
						<a href="javascript:void(0);" title="Select All" id="widget_code_button">Select All</a>
					</span>
				</div>
			</td>
		</tr>
	</tbody>
</table>

<div class="titlepage_admin">
	<h1>The <em>Cambridge Books Online</em> widget is also available on widgetbox.com</h1>
</div>

<a href="http://www.widgetbox.com/widget/cambridge-books-online-quicksearch" target="_blank">You can view the <em>Cambridge Books Online</em> Quick Search widget on widgetbox.com here.</a>
<script type="text/javascript" src="${pageContext.request.contextPath}/orgadmin/js/widget.cbo.quick.js" ></script>

src/ONLINE/WebContent/orgadmin/components/librarians/customize_search_whatisthis.jsp
<div class="titlepage_admin">
	<h1>What Is This?</h1>
</div>				
<p>If you click the "Add Cambridge Books Online as a search option in your browser toolbar" link, Cambridge Books Online is added as a search option in your browser's dropdown search box, which is located in the upper right corner of your browser window.</p>
To add <em>Cambridge Books Online</em> as a search option in your browser toolbar (for IE7/Firefox):
<ul>
	<li>Click on the "Add Cambridge Books Online as a search option in your browser toolbar" link.</li>
	<li>Click on the Add Provider button.</li>
	<li>You should now see <em>Cambridge Books Online</em> in the list of search providers in the dropdown search box at the top right of the screen. To select it, use the dropdown arrow and click on <em>Cambridge Books Online</em>.</li>
	<li>Enter a search term and press Enter or click the magnifying glass icon to initiate your search.</li>
</ul>				
<br />
To remove <em>Cambridge Books Online</em> from the list of search options:
<br />			
For IE7:
<ul>
	<li>Click on the dropdown arrow next to the search bar's magnifying glass icon</li>
	<li>Select "Change Search Defaults."</li>
	<li>Select Cambridge Books Online.</li>
	<li>Click Remove, then click OK.</li>
</ul>
<br />
For Firefox:
<ul>
	<li>Click on the dropdown arrow next to the icon of the current search engine.</li>
	<li>Select "Manage Search Engines."</li>
	<li>Select Cambridge Books Online.</li>
	<li>Click Remove, then click OK.</li>
</ul>			

src/ONLINE/WebContent/orgadmin/components/librarians/for_librarians_js.jsp
<%@ taglib uri="/WEB-INF/lib/online.tld" prefix="o" %>
<o:url var="current_dns" option="current_dns" />

<input type="hidden" id=current_dns value="${current_dns}" />
<input id="cjo_domain" type="hidden" value='<%=System.getProperty("cjo.domain") %>' />
<input type="hidden" id="page" value="${param.page}" />

<script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery/jquery-ui-1.8.9.custom.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/orgadmin/js/for_librarians.js"></script>

src/ONLINE/WebContent/orgadmin/components/librarians/marc_records.jsp
<%@ taglib uri="/WEB-INF/lib/c.tld" prefix="c" %>

<div class="titlepage_admin">
	<h1>Retrieve MARC Records</h1>	
</div>

<i>Cambridge Books Online</i> provides MARC records free of charge for
all titles in the collections. You may download a MARC21 format file (.mrc)
containing records of all titles available on the platform, or you may
download a MARC21 format file (.mrc) containing only those titles to which
your institution has purchased access.

<div id="rss_marcrecord">
	<p>
		<span class="icons_img rss_on">&nbsp;</span>To sign up for an RSS feed to be alerted to news related to Cambridge Books Online MARC records, 
		<a target="_blank" href="<%=System.getProperty("cjo.domain") %>data/rss/cbo_marcrecord_feed_rss.xml">click here</a>.
	</p>
</div>

<p>
	MARC record reader software such as MarcEdit will be required to add these
	files to your library system.
</p>

<div id="adminContent">
	<div id="body_admin">	
		<form name="counterStatForm" action="${pageContext.request.contextPath}/downloadMarcRecords" method="post">												
			<div>
			<!-- displays the orgList -->
			${marcRecords.initBean}				
				Download Records for: <select id="marcRecordsOption" name="option" class="select_02">	
					<option value="-1">All Published Books</option>
					<c:forEach var="orgMap" items="${marcRecords.orgList}">							
						<option value="${orgMap.bodyId}">${orgMap.name}</option>
					</c:forEach>				
				</select>
			</div><br>
		
			Order ID:&nbsp;<select id="orderIds" name="orderIds" style="width: 100px" class="select_02">
			</select>
		
			<!-- <div id="showOrderDate"> -->
			&nbsp;&nbsp;Order Date From:&nbsp;<input type="text" id="dateFrom" name="dateFrom" style="width:100px" /><!-- select id="dateFrom" name="dateFrom" style="width: 100px">
			</select>  -->
			&nbsp;To:&nbsp;<input type="text" id="dateTo" name="dateTo" style="width:100px"/><!-- <select id="dateTo" name="dateTo" style="width: 100px">
			</select> -->
			<br /><br />
			<div class="form_button">
				<span>
					<input name="cmd" type="submit" class="button" value="Download MARC Records" onclick="clearErrorMessage();" >
				</span>
			</div>
			<br />
			<c:if test="${param.error eq 'noMarcRecords'}">	
				<p id="errorMessage" style="color: red; padding-left: 5px; padding-top: 5px;">
					${param.errorMessage}
				</p>
			</c:if>
		</form>
	</div>
</div>
<div class="clear"></div>

src/ONLINE/WebContent/orgadmin/components/librarians/widget_whatisthis.jsp
<div class="titlepage_admin">
	<h1>What Is This?</h1>
</div>
<p>The <a target="_blank" href="/"><em>Cambridge Books Online</em></a> Widget provides a single interaction point with <a target="_blank" href="/"><em>Cambridge Books Online</em></a> directly from your blog, "start page," or a social networking site.</p>
<p>After placing the widget in your blog or start page, or your preferred social networking site, you will be able to run quick search from that page on the content of all <a target="_blank" href="/"><em>Cambridge Books Online</em></a>. The results will display in a new window or tab of your browser.</p>
<p>To get the widget, please click on the link <a target="_blank" href="${pageContext.request.contextPath}/orgadmin/for_librarians.jsf?page=wadd" >Add <em>Cambridge Books Online</em> widget to your Website</a>. Copy and paste the code and embed it to your page.</p>
<p>You may input a search term in the search box and press the button 'Search'. A Quick Search will be run on the term on all <a target="_blank" href="/"><em>Cambridge Books Online</em></a> and the results will display in a new window or tab of your browser.</p>